branch-defaults:
  master:
    environment: uploadservice-prod
  staging:
    environment: uploadservice-staging
global:
  application_name: *************
  default_ec2_keyname: *************
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
